FROM debian:stable-slim

LABEL Author="David Dikman <david@greycastle.se>"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qqy \
  && apt-get -qqy install \
       dumb-init gnupg wget ca-certificates apt-transport-https git \
       ttf-wqy-zenhei \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
  && apt-get update -qqy \
  && apt-get -qqy install google-chrome-unstable \
  && rm /etc/apt/sources.list.d/google-chrome.list \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

#RUN useradd headless --shell /bin/bash --create-home \
#  && usermod -a -G sudo headless \
#  && echo 'ALL ALL = (ALL) NOPASSWD: ALL' >> /etc/sudoers \
#  && echo 'headless:nopassword' | chpasswd

#RUN mkdir /data && chown -R headless:headless /data

# Install node 10
RUN wget -q -O -  https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs

# Install ruby and heroku for deployment
# procps for spawning chromedriver process
RUN apt-get update -qy \
    && apt-get install -y ruby-dev procps \
    && gem install dpl